---
- name: Provision Basic Setup
  hosts: base
  become: yes
  tasks:
  - name: "Update System"
    apt: update_cache=yes cache_valid_time=86400 upgrade=dist autoremove=yes

  - name: "Install unattended-upgrades"
    apt: pkg=unattended-upgrades state=present

  - name: "Check if reboot is required"
    stat: path=/var/run/reboot-required
    register: reboot_required
  
  - name: "Reboot server"
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
    when: reboot_required.stat.exists
  
  - name: "Waiting for server to come back"
    local_action: wait_for host={{ ansible_host }} port={{ ansible_port|default(22) }} state=started
    become: false
